id: P000720
initial_creation_type: ocr
source_metadata:
  id: bdr:W19961
  title: སུམ་རྟགས་བཤད་སྦྱར་ལེགས་བཤད་གཅེས་བསྡུས
  author: ''
  volumes:
    c64822d90b834b83ad143d0fa863e850:
      image_group_id: I5679
      title: ''
      volume_number: 1
      total_pages: 208
