id: P000720
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-16 16:38:56.137374
source_metadata:
  id: bdr:W19961
  title: སུམ་རྟགས་བཤད་སྦྱར་ལེགས་བཤད་གཅེས་བསྡུས
  author: ''
  volumes:
    c64822d90b834b83ad143d0fa863e850:
      image_group_id: I5679
      title: ''
      volume_number: 1
      total_pages: 208
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
