id: I82A7A48C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T00:38:25+00:00'
last_modified: '2022-06-07T12:44:49.669834+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W19961
  title: སུམ་རྟགས་བཤད་སྦྱར་ལེགས་བཤད་གཅེས་བསྡུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CE34:
      image_group_id: I5679
      title: ''
      total_pages: 208
      order: 1
      base_file: CE34.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
